/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_signup;

import javax.swing.JOptionPane;

public class Signup_Page extends javax.swing.JFrame {

    int xx, xy;
    
    public static String email;
    public static String password;
    public static String confirm_pass;
    
    public Signup_Page() {
        initComponents();
        
        lb_hide_pass.setVisible(false);
        lb_hide_confirm.setVisible(false);
    }

    void clean(){
      t_username.setText("Email Address");
      t_password.setText("********");
      t_confirm.setText("********");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_exit = new javax.swing.JLabel();
        bt_minimize = new javax.swing.JLabel();
        pict = new javax.swing.JLabel();
        ask_account = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        t_validasi = new javax.swing.JLabel();
        email_text = new javax.swing.JLabel();
        pass_text = new javax.swing.JLabel();
        confirm_text = new javax.swing.JLabel();
        lb_show_pass = new javax.swing.JLabel();
        lb_hide_pass = new javax.swing.JLabel();
        lb_show_confirm = new javax.swing.JLabel();
        lb_hide_confirm = new javax.swing.JLabel();
        show_pass = new javax.swing.JLabel();
        show_confirm = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        t_username = new javax.swing.JTextField();
        t_password = new javax.swing.JPasswordField();
        t_confirm = new javax.swing.JPasswordField();
        bt_signup = new javax.swing.JButton();
        logo_login = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
        });
        jPanel1.add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        bt_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_minimize.png"))); // NOI18N
        bt_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(bt_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 6, -1, -1));

        pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/picture.png"))); // NOI18N
        jPanel1.add(pict, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        ask_account.setText("Already have an account?");
        jPanel1.add(ask_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 397, -1, -1));

        welcome.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 102, 0));
        welcome.setText("Welcome!");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 190, 60));

        t_validasi.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(t_validasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 260, 20));

        email_text.setText("Email Address");
        jPanel1.add(email_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pass_text.setText("Password");
        jPanel1.add(pass_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        confirm_text.setText("Konfirmasi Password");
        jPanel1.add(confirm_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lb_show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/uncheck.png"))); // NOI18N
        lb_show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_show_passMouseClicked(evt);
            }
        });
        jPanel1.add(lb_show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, -1, -1));

        lb_hide_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check.png"))); // NOI18N
        lb_hide_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hide_passMouseClicked(evt);
            }
        });
        jPanel1.add(lb_hide_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, -1, -1));

        lb_show_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/uncheck.png"))); // NOI18N
        lb_show_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_show_confirmMouseClicked(evt);
            }
        });
        jPanel1.add(lb_show_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 307, -1, -1));

        lb_hide_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check.png"))); // NOI18N
        lb_hide_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hide_confirmMouseClicked(evt);
            }
        });
        jPanel1.add(lb_hide_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 307, -1, -1));

        show_pass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        show_pass.setForeground(new java.awt.Color(102, 102, 102));
        show_pass.setText("show password");
        jPanel1.add(show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 219, -1, -1));

        show_confirm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        show_confirm.setForeground(new java.awt.Color(102, 102, 102));
        show_confirm.setText("show password");
        jPanel1.add(show_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 310, -1, -1));

        bt_login.setBackground(new java.awt.Color(252, 251, 251));
        bt_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 102, 0));
        bt_login.setText("LOGIN");
        bt_login.setBorder(null);
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jPanel1.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 70, 30));

        t_username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("Email Address");
        t_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 36));

        t_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_password.setText("********");
        t_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, 36));

        t_confirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_confirm.setText("********");
        t_confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        t_confirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_confirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_confirmFocusLost(evt);
            }
        });
        t_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(t_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 260, 36));

        bt_signup.setBackground(new java.awt.Color(255, 102, 0));
        bt_signup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_signup.setForeground(new java.awt.Color(255, 255, 255));
        bt_signup.setText("SIGN UP");
        bt_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signupActionPerformed(evt);
            }
        });
        jPanel1.add(bt_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 260, 34));

        logo_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logo_login.setForeground(new java.awt.Color(255, 102, 0));
        logo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_human.png"))); // NOI18N
        logo_login.setText("SIGN UP");
        jPanel1.add(logo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 22, 160, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 690, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked
        dispose();
    }//GEN-LAST:event_bt_exitMouseClicked

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void bt_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signupActionPerformed
        if(t_password.getText().equals(t_confirm.getText())){
           email = t_username.getText();
           password = t_password.getText();

        Login_Page login = new Login_Page();
        login.setVisible(true);
        JOptionPane.showMessageDialog(null, "Sign Up berhasil!", "Notifikasi", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
       }
       else{
           t_validasi.setText("The password doesn't match");
           JOptionPane.showMessageDialog(null, "Sign up gagal. Mohon periksa kembali data Anda.", "Notifikasi", JOptionPane.ERROR_MESSAGE);
       } 
    }//GEN-LAST:event_bt_signupActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String username = t_username.getText();
            if(username.equals("Email Address")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String username = t_username.getText();
            if(username.equals("")||username.equals("Email Address")){
            t_username.setText("Email Address");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String pass = t_password.getText();
            if(pass.equals("********")){
            t_password.setText("");
        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String pass = t_password.getText();
            if(pass.equals("")||pass.equals("********")){
            t_password.setText("********");
        }

    }//GEN-LAST:event_t_passwordFocusLost

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        Login_Page login = new Login_Page();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_bt_loginActionPerformed

    private void t_confirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_confirmFocusGained
        String confirm = t_confirm.getText();
            if(confirm.equals("********")){
            t_confirm.setText("");
        }
    }//GEN-LAST:event_t_confirmFocusGained

    private void t_confirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_confirmFocusLost
        String confirm = t_confirm.getText();
            if(confirm.equals("")||confirm.equals("********")){
            t_confirm.setText("********");
        }
    }//GEN-LAST:event_t_confirmFocusLost

    private void t_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_confirmActionPerformed

    private void bt_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_bt_minimizeMouseClicked

    private void lb_show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_show_passMouseClicked
        lb_show_pass.setVisible(false);
        lb_hide_pass.setVisible(true);
        t_password.setEchoChar((char)0);
    }//GEN-LAST:event_lb_show_passMouseClicked

    private void lb_hide_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_passMouseClicked
        lb_show_pass.setVisible(true);
        lb_hide_pass.setVisible(false);
        t_password.setEchoChar('*');
    }//GEN-LAST:event_lb_hide_passMouseClicked

    private void lb_show_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_show_confirmMouseClicked
        lb_show_confirm.setVisible(false);
        lb_hide_confirm.setVisible(true);
        t_confirm.setEchoChar((char)0);
    }//GEN-LAST:event_lb_show_confirmMouseClicked

    private void lb_hide_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_confirmMouseClicked
        lb_show_confirm.setVisible(true);
        lb_hide_confirm.setVisible(false);
        t_confirm.setEchoChar('*');
    }//GEN-LAST:event_lb_hide_confirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ask_account;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bt_exit;
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel bt_minimize;
    private javax.swing.JButton bt_signup;
    private javax.swing.JLabel confirm_text;
    private javax.swing.JLabel email_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_hide_confirm;
    private javax.swing.JLabel lb_hide_pass;
    private javax.swing.JLabel lb_show_confirm;
    private javax.swing.JLabel lb_show_pass;
    private javax.swing.JLabel logo_login;
    private javax.swing.JLabel pass_text;
    private javax.swing.JLabel pict;
    private javax.swing.JLabel show_confirm;
    private javax.swing.JLabel show_pass;
    private javax.swing.JPasswordField t_confirm;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    private javax.swing.JLabel t_validasi;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
